### ISSUE TITLE
Missing datasets/assert directory

### ISSUE THREAD

**Issue by jose** [NougatCA/FineTuner#4]
Hi @NougatCA,

The `datasets.zip` file available [here](https://1drv.ms/u/s!Aj4XBdlu8BS0gf9b0e1Dze2AkxsqxA?e=p0Whot) is missing the `assert` directory.

```bash
$ python main.py --model codet5 --task assert --subset raw
==================== INITIALIZING ====================
Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: fp16

wandb: Currently logged in as: josecampos (uporto). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.10
wandb: Run data is saved locally in /tmp/FineTuner/src/wandb/run-20230301_121613-rg039n1c
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run codet5_assert_assert_raw
wandb: ⭐️ View project at https://wandb.ai/uporto/CodePTM_Evaluation
wandb: 🚀 View run at https://wandb.ai/uporto/CodePTM_Evaluation/runs/rg039n1c
==================== LOADING ====================
Loaded config 'T5Config' from 'Salesforce/codet5-base'
Loaded tokenizer 'RobertaTokenizerFast' from 'Salesforce/codet5-base', size: 32100
Loaded unwrapped model 'T5ForConditionalGeneration' from 'Salesforce/codet5-base'
Loaded model 'T5ForConditionalGeneration' from 'Salesforce/codet5-base'
Trainable parameters: 223M
Start loading train data from ../datasets/assert/assert/raw
Traceback (most recent call last):
  File "/tmp/FineTuner/src/main.py", line 113, in <module>
    main()
  File "/tmp/FineTuner/src/main.py", line 109, in main
    run_fine_tune(args, accelerator, run)
  File "/tmp/FineTuner/src/run_fine_tune.py", line 277, in run_fine_tune
    train_examples, train_dataset, train_dataloader = prepare_data(args, split="train", tokenizer=tokenizer)
  File "/tmp/FineTuner/src/data.py", line 504, in prepare_data
    examples = load_examples(args, split=split, aux_data=aux_data)
  File "/tmp/FineTuner/src/data.py", line 204, in load_examples
    with open(source_path, mode="r", encoding="utf-8") as source_f, \
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/assert/assert/raw/train_methods.txt'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run codet5_assert_assert_raw at: https://wandb.ai/uporto/CodePTM_Evaluation/runs/rg039n1c
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230301_121613-rg039n1c/logs
```

```bash
$ ls /tmp/FineTuner/datasets/
README.md  bug  clone  defect  generation  qa  retrieval  search  summarization  translation
```

Could you please update the zip file to also include the `assert` directory?  Thanks in advance.

--
Best,
Jose

**Comment by NougatCA** [comment]
Hi @jose ,

I'm sorry I forgot to include some datasets, including the assert dataset, into the published dataset. Now I have update the versions of the dataset both in [OneDrive](https://1drv.ms/u/s!Aj4XBdlu8BS0gf9b0e1Dze2AkxsqxA?e=wOGd4s) and [Zenodo](https://doi.org/10.5281/zenodo.7318109).

Thanks for your issue and sorry about the trouble.

**Comment by jose** [comment]
Thanks.
